# Jekyll website published using github pages
# ref: https://pages.github.com/versions/
# 
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# About/contact
author:
  name: bijumon
  url: https://github.com/bijumon/
  twitter: https://twitter.com/bijupunalor
  github:
    repo: https://github.com/bijumon/vfxwatch-com

# Setup
title: "VFX Watch"
tagline: "Visual Effects, Graphics and Gamedev News"
description: 'news visual-effects graphics graphics-programming vfx'
timezone: Asia/Kolkata

# Publishing 
url: https://www.vfxwatch.com
baseurl: ""
permalink: pretty
excerpt_separator: <!--more--> 
paginate: 10

# https://github.com/github/jekyll-commonmark-ghpages
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "table"]

# https://github.com/jekyll/jekyll-sass-converter
sass:
  sass_dir: _sass
    #  style: :compressed

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page"

# Google Analytics tracking
ga_analytics: G-PD905GD4PG

# Exclude from published site
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor
